In [ ]:
import numpy as np
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix)
type(matrix.shape[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


int

Даны матрицы A B C

Найти: А+В, В-А, A*C, A*B*C (руками и кодом)

Умножение будем рассматривать векторное

In [ ]:
#функции написанные самим, без библиотеки
def cod_sum_matrix(matrix_1: np.array, matrix_2: np.array)-> None:
    if matrix_1.shape == matrix_2.shape:
        matrix_res = np.zeros((matrix_2.shape[0], matrix_2.shape[1]),dtype = int)
        for i in range(matrix_2.shape[0]):
            for j in range(matrix_2.shape[1]):
                matrix_res[i][j] = matrix_1[i][j] + matrix_2[i][j]
    else:
        print("Error")
    print(matrix_res)

def cod_sub_matrix(matrix_1: np.array, matrix_2: np.array)-> None:
    if matrix_1.shape == matrix_2.shape:
        matrix_res = np.zeros((matrix_2.shape[0], matrix_2.shape[1]),dtype = int)
        for i in range(matrix_2.shape[0]):
            for j in range(matrix_2.shape[1]):
                matrix_res[i][j] = matrix_1[i][j] - matrix_2[i][j]
    else:
        print("Error")
    print(matrix_res)

def cod_mult_matrix(matrix_1: np.array, matrix_2: np.array)-> np.array:
    if matrix_1.shape[1] == matrix_2.shape[0]:
        matrix_res = np.zeros((matrix_1.shape[0], matrix_2.shape[1]), dtype=int)
        for i in range(matrix_1.shape[0]):
            for j in range(matrix_2.shape[1]):
                for k in range(matrix_1.shape[1]):
                    matrix_res[i][j] += matrix_1[i][k] * matrix_2[k][j]
    return matrix_res

def trans_matrix(matrix_1: np.array)->None:
    matrix_res = np.zeros((matrix_1.shape[0],matrix_1.shape[1]),dtype = int)
    for i in range(matrix_1.shape[0]):
        for j in range(matrix_1.shape[1]):
            matrix_res[j][i] = matrix_1[i][j]
    print(matrix_res)


In [ ]:
matrix_a =np.array([
    [1,2,4],
    [7,5,-2],
    [-2,1,3]
])
matrix_b =np.array([
    [-1,0,3],
    [2,-6,1],
    [-7,1,5]
])
matrix_c =np.array([
    [-2,3],
    [4,0],
    [7,-1]
])
cod_sum_matrix(matrix_a, matrix_b)
print()
cod_sub_matrix(matrix_b,matrix_a)
print()
matrix_ac = cod_mult_matrix(matrix_a,matrix_c)
print(f"{matrix_ac}\n")
matrix_ab = cod_mult_matrix(matrix_a,matrix_b)
matrix_abc = cod_mult_matrix(matrix_ab,matrix_c)
print(f"{matrix_abc}\n")
trans_matrix(matrix_a)

[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]

[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]

[[34 -1]
 [-8 23]
 [29 -9]]

[[ 193 -100]
 [ -50   35]
 [  92  -61]]

[[ 1  7 -2]
 [ 2  5  1]
 [ 4 -2  3]]


In [ ]:
#функции библиотеки
def sum_matrix(matrix_1: np.array, matrix_2: np.array)-> np.array:
    print("A + B :")
    matrix_res = matrix_1 + matrix_2
    print(matrix_res)


def subtraction_matrix(matrix_1: np.array,matrix_2: np.array)-> np.array:
    print("\nB - A:")
    matrix_res = matrix_1 - matrix_2
    print(matrix_res)


def mult_matrix_ac(matrix_1: np.array,matrix_2: np.array)-> np.array:
    print("\nA * C:")
    matrix_res = np.dot(matrix_1,matrix_2)
    print(matrix_res)

def mult_matrix_abc(matrix_1: np.array,matrix_2: np.array, matrix_3: np.array)-> np.array:
    print("\nA * B * C:")
    matrix_res = np.dot(np.dot(matrix_1,matrix_2),matrix_3)
    print(matrix_res)

In [ ]:
matrix_a =np.array([
    [1,2,4],
    [7,5,-2],
    [-2,1,3]
])
matrix_b =np.array([
    [-1,0,3],
    [2,-6,1],
    [-7,1,5]
])
matrix_c =np.array([
    [-2,3],
    [4,0],
    [7,-1]
])

sum_matrix(matrix_a, matrix_b)
subtraction_matrix(matrix_b,matrix_a)
mult_matrix_ac(matrix_a, matrix_c)
mult_matrix_abc(matrix_a, matrix_b,matrix_c)

A + B :
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]

B - A:
[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]

A * C:
[[34 -1]
 [-8 23]
 [29 -9]]

A * B * C:
[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [ ]:
matrix_a =np.array([
    [0,3,4],
    [-7,1,-2],
    [2,-1,3]
])
matrix_b =np.array([
    [1,2,4],
    [7,0,-2],
    [-3,-2,5]
])
matrix_c =np.array([
    [-3,2],
    [0,4],
    [-1,7]
])

sum_matrix(matrix_a, matrix_b)
subtraction_matrix(matrix_b,matrix_a)
mult_matrix_ac(matrix_a, matrix_c)
mult_matrix_abc(matrix_a, matrix_b,matrix_c)

A + B :
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]

B - A:
[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]

A * C:
[[ -4  40]
 [ 23 -24]
 [ -9  21]]

A * B * C:
[[ -41   84]
 [  22 -308]
 [  17  139]]


In [ ]:
matrix_a =np.array([
    [5,2,9],
    [7,0,-2],
    [-2,1,6]
])
matrix_b =np.array([
    [1,-2,1],
    [7,5,-2],
    [-2,8,3]
])
matrix_c =np.array([
    [-2,3],
    [4,5],
    [0,-1]
])

sum_matrix(matrix_a, matrix_b)
subtraction_matrix(matrix_b,matrix_a)
mult_matrix_ac(matrix_a, matrix_c)
mult_matrix_abc(matrix_a, matrix_b,matrix_c)

A + B :
[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]

B - A:
[[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]

A * C:
[[ -2  16]
 [-14  23]
 [  8  -7]]

A * B * C:
[[ 286  335]
 [-142 -118]
 [ 242  250]]


In [ ]:
matrix_a =np.array([
    [1,-2,8],
    [7,5,-2],
    [-2,3,0]
])
matrix_b =np.array([
    [0,2,4],
    [1,-3,-2],
    [-2,1,3]
])
matrix_c =np.array([
    [0,3],
    [5,-4],
    [7,-1]
])

sum_matrix(matrix_a, matrix_b)
subtraction_matrix(matrix_b,matrix_a)
mult_matrix_ac(matrix_a, matrix_c)
mult_matrix_abc(matrix_a, matrix_b,matrix_c)

A + B :
[[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]

B - A:
[[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]

A * C:
[[ 46   3]
 [ 11   3]
 [ 15 -18]]

A * B * C:
[[ 304 -150]
 [  69   27]
 [-163   75]]


In [ ]:
matrix_a =np.array([
    [9,2,4],
    [7,5,-5],
    [6,-2,3]
])
matrix_b =np.array([
    [8,2,4],
    [0,1,-3],
    [-2,1,6]
])
matrix_c =np.array([
    [-2,0],
    [4,8],
    [1,-1]
])

sum_matrix(matrix_a, matrix_b)
subtraction_matrix(matrix_b,matrix_a)
mult_matrix_ac(matrix_a, matrix_c)

A + B :
[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]

B - A:
[[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]

A * C:
[[ -6  12]
 [  1  45]
 [-17 -19]]
